### ISSUE TITLE
Wrap content height

### ISSUE THREAD

**Issue by sedestrian** [LucasMucGH/BottomSheet#17]
Hello, would it be possible to have the height expand with the content?
My specific usecase is a bottomsheet that is hidden by default and then it expands to show a few sort order options, and i wold like the sheet to be the height of the view inside it

**Comment by LucasMucGH** [comment]
Hello,

Thank you for your suggestion, this is something I will look forward to implement. I will now close this issue because the requested feature has been moved to #11.

Greetings,
Lucas
