### ISSUE TITLE
Xcode 13: Compiler-Error UIApplication.shared

### ISSUE THREAD

**Issue by Feuerwerk** [LucasMucGH/BottomSheet#19]
The method

private func endEditing() -> Void {
    UIApplication.shared.windows.filter{$0.isKeyWindow}.first?.endEditing(true)
}

throws a compiler error using BottomSheet in Xcode 13 Beta 3 for an iOS project (Deployment Target 15) saying that UIApplication extensions are not available for iOS and you should rely on ViewController functionality.

**Comment by LucasMucGH** [comment]
Thank you for pointing this out.
Unfortunately I’m currently not committed to use the Xcode betas, because I had a lot of trouble last year and they completely broke developing  and even some of my project.
As soon as Xcode 13 is finally released I will fix all build and design issues and test the project fully for iOS 15.

For now you can do your own testing and research and if you find a Solution working for iOS 13, 14 and 15 don’t hesitate to open a pull request.

I will leave this issue open, as it is technically a bug, but before the final release of Xcode 13 i won’t fix it.

Greetings Lucas

**Comment by Wouter01** [comment]
This might help: https://twitter.com/twannl/status/1415643870512226307

**Comment by LucasMucGH** [comment]
@Wouter01 Yes thank you. I saw your fork, and if you could fix it (I’m unable to test it, because I’m not using Xcode 13) it would be nice if you would open a pull request.

Greetings Lucas

**Comment by Wouter01** [comment]
> @Wouter01 Yes thank you. I saw your fork, and if you could fix it (I’m unable to test it, because I’m not using Xcode 13) it would be nice if you would open a pull request.
> 
> Greetings Lucas

I did have a look but wasn't able to fix it. I got it working on another library with this method, so it will probably be solvable in this way, but I currently do not have time to take a further look at it.

**Comment by LucasMucGH** [comment]
Ah ok, no worries 👍

**Comment by Feuerwerk** [comment]
I've tested it with the information in the twitter feed mentioned by @Wouter01 but this doesn't seem to work. As far as i understand this piece of code must be moved in a separate file which must be excluded from the iOSApplicationExtension-Target. I'm currently thinking of two files both containing only the function endEditing(). One containing the implementation as it is currently and one is empty (for the moment). Then the empty one must be used with the iOSApplicationExtension-Target and the other file must be used with all other targets. But i have little knowledge about the package-description  to explicitly include / exclude a file from a specific target.

**Comment by LucasMucGH** [comment]
Thank you all for your help regarding this problem.
As soon as Xcode 13 is released I will have a look and first try to fix it using @Wouter01 solution and if it doesn't work I will try to implement @Feuerwerk solution.
But maybe I will discover another way, with will work for every iOS version.

@Feuerwerk @Wouter01 could one of you please test this code and see if it works for now?
``` swift

private func endEditing() -> Void {
     if #available(iOS 15, *) {
         //No solution right now
     } else {
          UIApplication.shared.windows.filter{$0.isKeyWindow}.first?.endEditing(true)
     }
}
```
Thank you,
Lucas

**Comment by Feuerwerk** [comment]
@LucasMucGH I tested this already, doesn't work. because #available is a test at runtime but UIApplication.shared is not available at compile time.

**Comment by LucasMucGH** [comment]
Ah ok, thank you.

**Comment by Feuerwerk** [comment]
There is a discussion about this "feature" at swift.org
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333

**Comment by Feuerwerk** [comment]
I may have found a simple solution: https://github.com/LucasMucGH/BottomSheet/pull/20
