### ISSUE TITLE
Shadow for same color bottomsheet and main page content

### ISSUE THREAD

**Issue by sedestrian** [LucasMucGH/BottomSheet#22]
Could we have the ability to add a shadow to separate the bottomsheet from the main content when the color is the same?

**Comment by LucasMucGH** [comment]
As of commit 95583e5 this feature is now implemented. A new release won't be published for now, so please use the `main` branch in your Package Manager.

Have a look over [here](https://github.com/LucasMucGH/BottomSheet#options) to see how to use it; to enable the default shadow just use `.shadow()`, if you want to customise anything e.g. the color use `.shadow(color: .red)`.

Greetings,
Lucas
