### ISSUE TITLE
Does BottomSheetView resize when position binding changes?

### ISSUE THREAD

**Issue by VictorBogatyrev** [LucasMucGH/BottomSheet#29]
I have several content views which are into BottomSheet depending on state in ViewModel. But when I change position binding nothing happens.

**Comment by LucasMucGH** [comment]
Hello Victor,

I’m not sure If understand your issue correctly. Could you please provide a photo or video and some source code, to make it easier for me to identify your problem and help you.

Greetings,
Lucas

**Comment by LucasMucGH** [comment]
@VictorBogatyrev If you don't answer until New Year, I will close this issue.

But maybe this answers your question: 
https://www.hackingwithswift.com/quick-start/swiftui/how-to-run-some-code-when-state-changes-using-onchange
https://developer.apple.com/documentation/combine/performing-key-value-observing-with-combine

**Comment by VictorBogatyrev** [comment]
Sorry for long answering. I resolved my problem by writing own BottomSheet view, because I didn't find any option for fully dynamic height
