### ISSUE TITLE
Implicit animation bug with NavigationView

### ISSUE THREAD

**Issue by artemelianov** [LucasMucGH/BottomSheet#31]
Hi
Thanks for this amazing library! 

I've found a new bug. If we embed this sheet at the start, we will see an implicit animation. First point of the view is .zero, so we can se the animation i suppose 
Any ideas how to handle it? 

https://user-images.githubusercontent.com/29770918/138312996-875c1917-50ac-47bb-833d-284181ef075c.mov

**Comment by LucasMucGH** [comment]
Hello, thank you for your kind words and for your bug report.

Would you mind to share some code for reproducing this behavior, to help me understanding what causes this bug and how to fix it.

Greetings Lucas
