### ISSUE TITLE
swipeToDismiss with ScrollView

### ISSUE THREAD

**Issue by kushsolitary** [LucasMucGH/BottomSheet#34]
Hi, 

First of all, this library is very helpful and makes it super easy to implement bottom sheets. I am trying to create a bottom sheet that has a ScrollView inside but I want to make it work with `swipeToDismiss`. Currently, with ScrollView as the root container of the bottom sheet, dragging the sheet just makes the content bounce. 

I think dragging down on the ScrollView when the `contentOffset` is 0 should dismiss the bottom sheet. What do you think?

**Comment by LucasMucGH** [comment]
Yeah the concept of this idea is already on my pipeline in #11
But I don't think it would make sense, to dismiss the `ScrollView` instantaneously, after the `contentOffset` of the `ScrollView` is 0. After it is 0, the `bottomSheet` should get draged down instead. And only if the `bottomSheet` is below a threshold, it gets dismissed. What do you think?

**Comment by LucasMucGH** [comment]
In favour of #39 im closing this issue now.
