### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by jrafaelahmedov** [LucasMucGH/BottomSheet#35]
Hi dears. Firstly, thank you this awesome library! How can i detect drag event?  I am only catch this event at the ending of dragging. But i want to detect this during the dragging

**Comment by iYasha** [comment]
> Hi dears. Firstly, thank you this awesome library! How can i detect drag event? I am only catch this event at the ending of dragging. But i want to detect this during the dragging

Hi jrafaelahmedov, how you catch drag event ?

**Comment by LucasMucGH** [comment]
Yes, as to my knowledge `.bottomSheet` breaks the `.dragGesture` modifier. This is probably because it is used by `.bottomSheet` itself or because the BottomSheet changes its height and offset, which causes confusion for the `.dragGestrue` event. I am going to work on this.

**Comment by LucasMucGH** [comment]
Hello Rafael Ahmedov and iYasha,

I realised that the native `. simultaneousGesture` modifier works just fine: 

```swift
Color.black
            .ignoresSafeArea()
            .bottomSheet(bottomSheetPosition: self.$bottomSheetPosition, options: []) {
                    Text("Hello BottomSheet!")
            }
            .simultaneousGesture(
                DragGesture()
                    .onChanged({ value in
                        print(value)
                    })
                    .onEnded({ value in
                        print(value)
                    })
            )
```

Only when using a scroll view it stops working, but this is a general SwiftUI problem (as to my knowledge).

If I misunderstood you, don't hesitate to tell me.

Greetings from Germany,
Lucas
