### ISSUE TITLE
Option for specifiying sheet height as an absolute value

### ISSUE THREAD

**Issue by anqus** [LucasMucGH/BottomSheet#37]
Hello,

First of all thanks for the great package, it's awesome!

I have made a few small changes on a local branch, and was hoping to PR them in to main, as I think others may find them useful. 

The changes allow you to specify the sheet height as an absolute value rather than a percentage, which can be flagged in the sheet options. 

Basically this means that if you specify the sheet position as 200 point, it will show as 200 point across all devices, and device orientations. Useful if the contents are fixed, and require the same height in all situations.

Happy to create a quick PR and merge in if you think it'd come in handy!

Cheers.

**Comment by LucasMucGH** [comment]
Thank you for your idea and the kind words. It is already in the #38 PullRequest or the `#new-year-update` branch. If you want, you can test it and tell me it works as expected.
