### ISSUE TITLE
`List` inside `.appleScrollBehavior` sheet is invisible

### ISSUE THREAD

**Issue by CaryAndo** [LucasMucGH/BottomSheet#52]
If you create a `List` with items inside the main content of a sheet in the `.top` position, the List is invisible.

**Comment by LucasMucGH** [comment]
Yes, like mentioned in similar issues before, I will remove appleScrollBehavior soon, because it is really buggy and messes with ScrollViews, Lists and Gestures. No support for appleScrollBehavior will be provided anymore.

**Comment by lucaszischka** [comment]
This is not a bug of this library. Just try this and you will realise that a list always disappear inside of a ScrollView:
```swift
ScrollView {
    List {
        Rectangle()
            .foregroundColor(.blue)
            .frame(height: 400)
            .padding([.trailing, .leading], 20)
        Rectangle()
            .foregroundColor(.green)
            .frame(height: 400)
            .padding([.trailing, .leading], 20)
        Rectangle()
            .foregroundColor(.yellow)
            .frame(height: 400)
            .padding([.trailing, .leading], 20)
    }
}
```
